title: "My Startpage"          # Was im Header erscheinen soll
description: ""
author: ""                     # Leer lassen oder weglassen

# Theme (falls du eines nutzt)
theme: hacker                  # oder weglassen wenn kein Jekyll-Theme

# GitHub Pages Plugins
#plugins:
#  - jekyll-feed

